### ISSUE TITLE
Standard streamdeck audio up/down buttons taken over?

### ISSUE THREAD

**Issue by willmeyer** [JavanPoirier/AudioMixer#27]
Thank you for the work here. I'm trying to have app-specific buttons, using your plugin, as well as overall system volume buttons. Ideally your plugin's up and down buttons would apply to overall system volume if no button is selected. Barring that, I can add the system volume buttons in addition, though those seem to do nothing when no app is selected, and apply to that source when the button is selected. Any take on the expected behavior here?

**Comment by JavanPoirier** [comment]
Overall system volume buttons are not supported. The buttons for volume are static buttons, not system wide. It just means they are always visible. I did not include system volume support as most keyboards have this. For the volume controls to work you must have a selected application. As for app specific buttons, those are supported through the static application feature.

**Comment by willmeyer** [comment]
just a thank you, for the work and also the reply.
